### ISSUE TITLE
Obsolete project configurations and provided guide

### ISSUE THREAD

**Issue by Semeruk** [googlecodelabs/android-tv-leanback#4]
Please update the project and guide to fit most of developers needs. I'm talking about obsolete "compile", minSdk number, minSdk in manifest file, updating libraries' versions, etc and the same is with provided instruction (https://codelabs.developers.google.com/codelabs/androidtv-adding-leanback/index.html?index=..%2F..%2Findex#0).

I've spent a lot of time by fixing/editing these issues to make the app sync and compile properly, instead of straight dive into the app on emulator after each completed step from the guide.

Thanks!

**Comment by mikebonnell** [comment]
Resolved with this [PR](https://github.com/googlecodelabs/android-tv-leanback/pull/5). Thanks for raising the issue.

**Comment by Semeruk** [comment]
@mikebonnell thank you.
